import './styles.css';
import type Phaser from 'phaser';
import { loadBootstrap, submitRun } from './api.js';
import { createGame } from './game.js';
import type { BootstrapData, Loadout, RunSummary, Screen } from './models.js';

const app = document.querySelector<HTMLDivElement>('#app')!;
let data: BootstrapData | null = null;
let game: Phaser.Game | null = null;
let screen: Screen = 'briefing';
let loadout: Loadout = 'ward';
let summary: RunSummary | null = null;
let stats = { depth: 1, health: 3, relics: 0 };
let toastTimer = 0;

function escapeHtml(value: string) { const node=document.createElement('span'); node.textContent=value; return node.innerHTML; }
function formatTime(ms:number){const seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function countdown(){const now=new Date();const next=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1);const s=Math.max(0,Math.floor((next-Date.now())/1000));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function codename(seed:string){const a=['ASHEN','HOLLOW','IRON','QUIET','CINDER'];const b=['CHOIR','VAULT','MOUTH','LANTERN','THRESHOLD'];let n=0;for(const c of seed)n=(n*31+c.charCodeAt(0))>>>0;return `${a[n%a.length]} ${b[(n>>>3)%b.length]}`;}
function shell(content:string){return `<div class="app"><header class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true"></span><span>DAILY DESCENT</span></div><div class="top-actions"><span class="status">EXPEDITION LIVE</span><button class="icon-button" id="sound" aria-label="Toggle sound">◒</button><button class="icon-button" id="help" aria-label="How today works">?</button></div></header><main class="shell">${content}</main></div>`;}

function renderLoading(){app.innerHTML=shell(`<section class="hero-panel" aria-busy="true"><span class="eyebrow">Establishing torchlink</span><h1>Reading the stone.</h1><p class="lede">Recovering today’s shared map, warnings, and the echoes of delvers who entered before you.</p></section>`);}
function renderError(message:string){app.innerHTML=shell(`<section class="hero-panel"><span class="eyebrow">Torchlink interrupted</span><h1>The passage went dark.</h1><p class="lede">${escapeHtml(message)} Your daily attempt has not been consumed.</p><div class="hero-actions"><button class="primary" id="retry">Reconnect</button></div></section>`);document.querySelector('#retry')?.addEventListener('click',boot);}

function renderBriefing(){if(!data)return;screen='briefing';const progress=Math.min(100,(data.seed.todayGoalProgress/25)*100);const top=data.leaderboard[0];app.innerHTML=shell(`<div class="briefing">
<section class="hero-panel"><div class="depth-lines" aria-hidden="true"></div><span class="eyebrow">Expedition ${escapeHtml(data.seed.dateKey)} · Site 01</span><h1>Everyone gets the same darkness.</h1><p class="lede">One map. One ranked descent. Every ghost is a redditor who went first—and every warning you leave may save the next.</p><div class="hero-actions"><button class="primary" id="descend">Light the torch</button><button class="secondary" id="community">Study the expedition</button></div></section>
<aside class="side-stack"><section class="panel"><div class="panel-title"><div><span class="eyebrow">Today’s site</span><h2>${codename(data.seed.seed)}</h2></div><span class="countdown" data-countdown>${countdown()}</span></div><div class="metric"><span>Condition</span><b>Ember famine</b></div><div class="metric"><span>Top delver</span><b>${top?`u/${escapeHtml(top.username)} · ${top.depth}`:'No return yet'}</b></div><div class="metric"><span>Your attempt</span><b>Unspent</b></div></section>
<section class="panel"><div class="panel-title"><h3>Collective breach</h3><span class="eyebrow">${data.seed.todayGoalProgress}/25</span></div><div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div><div class="progress-meta"><span>Reach depth 5 to add your torch</span><b>${Math.round(progress)}%</b></div></section>
<section class="panel"><div class="panel-title"><h3>Choose one keepsake</h3><span class="eyebrow">Fair play</span></div><div class="choices">${choice('ward','Ash ward','Ignore the first wound')}${choice('thread','Red thread','Move with less delay')}${choice('spark','Last spark','Brighter path memory')}</div></section>
<section class="panel"><div class="panel-title"><h3>Signals below</h3><span class="eyebrow">Live</span></div><div class="signal-list"><div class="signal"><i class="sig-icon">×</i><div><strong>${data.seed.epitaphStats['Spike Trap']||0} fell to mechanisms</strong><span>Warnings flare when you approach</span></div></div><div class="signal"><i class="sig-icon">◇</i><div><strong>${data.ghosts.length} echoes recovered</strong><span>Their routes remain in the stone</span></div></div></div></section></aside></div>`);
wireGlobal();document.querySelector('#descend')?.addEventListener('click',startGame);document.querySelector('#community')?.addEventListener('click',renderCommunity);document.querySelectorAll<HTMLButtonElement>('[data-loadout]').forEach(b=>b.addEventListener('click',()=>{loadout=b.dataset.loadout as Loadout;renderBriefing();}));}
function choice(id:Loadout,name:string,desc:string){return `<button class="choice ${loadout===id?'active':''}" data-loadout="${id}" aria-pressed="${loadout===id}"><b>${name}</b><small>${desc}</small></button>`;}

function startGame(){if(!data)return;screen='game';app.innerHTML=shell(`<div class="game-layout"><section class="game-stage" aria-label="Daily dungeon game"><div id="game"></div><div class="hud"><div class="hud-block"><div class="hud-label">Depth</div><div class="hud-value" id="depth">01</div></div><div class="hud-block"><div class="hud-label">Torch / relics</div><div><span class="hud-value health" id="health">●●●</span> <span class="hud-value" id="relics">0</span></div></div></div><div class="toast" id="toast" role="status">Find the next room. Arrow keys, WASD, swipe, or controls.</div></section><aside class="game-rail"><section class="panel compact"><span class="eyebrow">Shared layer</span><div class="metric"><span>Ghost echoes</span><b>${data.ghosts.length}</b></div><div class="metric"><span>Warnings</span><b>${data.markers.length}</b></div><div class="metric"><span>Daily condition</span><b>Ember famine</b></div></section><section class="panel compact"><span class="eyebrow">Field note</span><p style="font-size:12px;line-height:1.6;color:#b8b9b0;margin-top:10px">Faint cyan lights are other delvers. Magenta pulses are warnings they left behind. Green relics advance the shared expedition.</p></section><section class="panel compact dpad-panel"><span class="eyebrow">Move</span><div class="dpad" aria-label="Directional controls"><button class="up" data-dir="U" aria-label="Move up">↑</button><button class="left" data-dir="L" aria-label="Move left">←</button><button class="down" data-dir="D" aria-label="Move down">↓</button><button class="right" data-dir="R" aria-label="Move right">→</button></div></section><button class="secondary" id="abandon">End expedition</button></aside></div>`);wireGlobal();game=createGame('game',data,{onStats:(depth,health,relics)=>{stats={depth,health,relics};const d=document.querySelector('#depth'),h=document.querySelector('#health'),r=document.querySelector('#relics');if(d)d.textContent=String(depth).padStart(2,'0');if(h)h.textContent='●'.repeat(health)+'○'.repeat(3-health);if(r)r.textContent=String(relics);},onMessage:showToast,onFinish:finishRun},loadout);document.querySelectorAll<HTMLButtonElement>('[data-dir]').forEach(b=>b.addEventListener('pointerdown',()=>game?.events.emit('step',b.dataset.dir)));document.querySelector('#abandon')?.addEventListener('click',()=>finishRun({depth:stats.depth,duration:0,cause:'Turned Back',position:{x:0,y:0},moves:'0,0|',relics:stats.relics,warningsSeen:0}));wireSwipe();}
function wireSwipe(){let x=0,y=0;const el=document.querySelector<HTMLElement>('.game-stage');el?.addEventListener('pointerdown',(e:PointerEvent)=>{x=e.clientX;y=e.clientY});el?.addEventListener('pointerup',(e:PointerEvent)=>{const dx=e.clientX-x,dy=e.clientY-y;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;game?.events.emit('step',Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');});}
function showToast(message:string){const el=document.querySelector<HTMLElement>('#toast');if(!el)return;el.textContent=message;el.style.opacity='1';clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>el.style.opacity='.25',2600);}
async function finishRun(value:RunSummary){summary=value;game?.destroy(true);game=null;if(data&&value.duration>0)submitRun(value,data.seed.seed).catch(()=>undefined);renderResult();}

function renderResult(){if(!data||!summary)return;screen='result';const rank=Math.max(1,data.leaderboard.findIndex(e=>e.depth<=summary!.depth)+1);app.innerHTML=shell(`<div class="result"><section class="hero-panel result-hero"><span class="eyebrow">Expedition sealed · ${escapeHtml(summary.cause)}</span><div class="result-number">${String(summary.depth).padStart(2,'0')}</div><h1 style="font-size:clamp(36px,5vw,68px)">${summary.depth>=8?'The dark learned your name.':'Your light remains below.'}</h1><div class="result-grid"><div class="result-stat"><b>${formatTime(summary.duration)}</b><span>time below</span></div><div class="result-stat"><b>${summary.relics}</b><span>echoes recovered</span></div><div class="result-stat"><b>#${rank}</b><span>projected rank</span></div></div><p class="story">You carried the ${loadout==='ward'?'Ash Ward':loadout==='thread'?'Red Thread':'Last Spark'} to depth ${summary.depth}. ${summary.relics?`You returned ${summary.relics} lost ember${summary.relics===1?'':'s'} to the expedition.`:'The stone kept what you passed.'} Tomorrow, the map changes—but this route will still warn those behind you.</p><div class="hero-actions"><button class="primary" id="expedition">See what we changed</button><button class="secondary" id="home">Tomorrow’s briefing</button></div></section><aside class="side-stack"><section class="panel"><div class="panel-title"><h3>Today’s survivors</h3><span class="eyebrow">Daily</span></div>${leaderboard(data.leaderboard)}</section><section class="panel"><span class="eyebrow">Return signal</span><h3 style="margin-top:8px">A new site opens in</h3><div class="result-number" style="font-size:32px;margin:15px 0" data-countdown>${countdown()}</div><p style="font-size:12px;color:#9b9d96;line-height:1.6">A fresh shared dungeon, a new modifier, and the result of today’s collective breach.</p></section></aside></div>`);wireGlobal();document.querySelector('#expedition')?.addEventListener('click',renderCommunity);document.querySelector('#home')?.addEventListener('click',renderBriefing);}
function leaderboard(entries:BootstrapData['leaderboard']){if(!entries.length)return `<p style="color:#9b9d96;font-size:12px">No ranked survivors yet. The first footprint could be yours.</p>`;return `<div class="leader-list">${entries.slice(0,8).map((e,i)=>`<div class="leader"><span class="leader-rank">${String(i+1).padStart(2,'0')}</span><b>u/${escapeHtml(e.username)}</b><span class="leader-score">D${e.depth}<small>${formatTime(e.duration)}</small></span></div>`).join('')}</div>`;}

function renderCommunity(){if(!data)return;screen='community';app.innerHTML=shell(`<div class="result"><section class="hero-panel result-hero"><span class="eyebrow">The shared expedition</span><h1 style="font-size:clamp(44px,7vw,84px)">No run disappears.</h1><p class="lede">Deaths become warnings. Routes become echoes. Recovered relics push open tomorrow’s sealed chamber.</p><div class="result-grid"><div class="result-stat"><b>${data.ghosts.length}</b><span>ghost routes</span></div><div class="result-stat"><b>${data.markers.length}</b><span>field warnings</span></div><div class="result-stat"><b>${data.seed.todayGoalProgress}</b><span>deep torches</span></div></div><p class="story">Discussion prompt: at the first Ember Shrine, did you restore your torch—or keep the offering for the lower vault?</p><div class="hero-actions"><button class="primary" id="back">${summary?'Return to report':'Return to briefing'}</button></div></section><aside class="side-stack"><section class="panel"><div class="community-tabs"><button class="active">Daily board</button><button>Echoes</button><button>Warnings</button></div>${leaderboard(data.leaderboard)}</section><section class="panel"><div class="panel-title"><h3>Tomorrow’s unlock</h3><span class="eyebrow">Community</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,data.seed.todayGoalProgress/25*100)}%"></div></div><p style="font-size:12px;color:#9b9d96;line-height:1.6;margin-top:12px">If 25 delvers reach depth 5, every player enters tomorrow with the Cartographer’s Mark revealed.</p></section></aside></div>`);wireGlobal();document.querySelector('#back')?.addEventListener('click',()=>summary?renderResult():renderBriefing());}

function wireGlobal(){document.querySelector('#help')?.addEventListener('click',()=>alert('One shared dungeon opens each UTC day. Your first run is ranked. Follow ghost echoes, heed community warnings, recover relics, and leave knowledge for the next delver.'));const timer=window.setInterval(()=>document.querySelectorAll('[data-countdown]').forEach(e=>e.textContent=countdown()),1000);window.setTimeout(()=>clearInterval(timer),3600000);}
async function boot(){renderLoading();try{data=await loadBootstrap();renderBriefing();}catch(error){renderError(error instanceof Error?error.message:'Could not reach the expedition.');}}
boot();
